In [4]:
import pandas as pd
import numpy as np
top3_corr = pd.read_csv('datasets/top3_corr.csv')
top3_corr = top3_corr.fillna('')
top3_corr

              Feature Name    Normal       DOS     Probe       R2L       U2R
0                logged in    0.7953 -0.754107
1                    count  -0.75297  0.762798
2             service_http  0.744731  0.720145
3            service_eco_i                          0.48
4   dst_host_diff_srv_rate                      0.468716
5            diff_srv_rate                      0.427723
6                      hot                                0.449503
7           is_guest_login                                0.356408
8              service_ftp                                0.328919
9               root_shell                                          0.486117
10          service_telnet                                          0.207959
11              num_shells                                          0.125231