In [1]:
import pandas as pd
import numpy as np

Load the dataset file:

In [2]:
dataset_file = 'kddcup.data_10_percent_corrected.csv'
feature_names = pd.read_csv('feature_names.csv', header=None)
kdd_names = feature_names.iloc[:,0].values

kdd = pd.read_csv(dataset_file, names=kdd_names)

Reclassify all attack types into four different classes and

In [3]:
kddFourClasses = kdd.copy()
dos   = ['neptune.', 'land.', 'pod.', 'smurf.', 'teardrop.', 'back.', 'worm.', 'udpstorm.', 'processtable.', 'apache2.']
probe = ['ipsweep.','satan.','nmap.','portsweep.','mscan.','saint.']
R2L   = ['ftp_write.','guess_passwd.', 'imap.','multihop.','phf.'
         ,'spy.','warezclient.','warezmaster.','snmpguess.','named.','xlock.','snmpgetattack.','httptunnel.','sendmail.']
U2R   = ['buffer_overflow.','loadmodule.','perl.','rootkit.','ps.','xterm.','sqlattack.']

kddFourClasses['attack_type'].values[kddFourClasses['attack_type'].isin(dos)] = 'dos'
kddFourClasses['attack_type'].values[kddFourClasses['attack_type'].isin(probe)] = 'probe'
kddFourClasses['attack_type'].values[kddFourClasses['attack_type'].isin(R2L)] = 'R2L'
kddFourClasses['attack_type'].values[kddFourClasses['attack_type'].isin(U2R)] = 'U2R'

kddFourClassesEncoded = pd.get_dummies(kddFourClasses, columns=['protocol_type','flag','service'])
#move the attack_type column to the 
attackType = kddFourClassesEncoded.pop('attack_type')
kddFourClassesEncoded['attack_type'] = attackType

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Columns: 119 entries, duration to service_whois
dtypes: float64(15), int64(23), object(1), uint8(80)
memory usage: 184.7+ MB

In [7]:
kddFourClassesEncoded

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,service_tftp_u,service_tim_i,service_time,service_urh_i,service_urp_i,service_uucp,service_uucp_path,service_vmnet,service_whois,attack_type
0,0,181,5450,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
1,0,239,486,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
2,0,235,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
3,0,219,1337,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
4,0,217,2032,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494016,0,310,1881,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
494017,0,282,2286,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
494018,0,203,1200,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
494019,0,291,1200,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.
494020,0,219,1234,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,normal.